name: mntcs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo add-apt-repository -y ppa:neurobin/ppa
          sudo apt-get update
          sudo apt-get install -y libc6-dev shc dh-make devscripts
          cd $GITHUB_WORKSPACE/build
          ./build.sh

      - name: Package
        run: |
          ls -la $GITHUB_WORKSPACE/build/
          mkdir $GITHUB_WORKSPACE/out
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-5)
          cp $GITHUB_WORKSPACE/build/*.deb $GITHUB_WORKSPACE/out/mntcs-${SHORT_SHA}.deb

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: mntcs
          path: out/*
