name: mntcs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo add-apt-repository -y ppa:neurobin/ppa
          sudo apt-get update
          sudo apt-get install -y libc6-dev shc dh-make devscripts
          cd $GITHUB_WORKSPACE/build
          ./build.sh

      - name: Package
        run: |
          ls -la $GITHUB_WORKSPACE/build/
          cp $GITHUB_WORKSPACE/build/*.deb $GITHUB_WORKSPACE/build/mntcs.deb

      - name: Publish
      uses: actions/upload-artifact@v1
      with:
        name: mntcs.deb
        path: $GITHUB_WORKSPACE/build/mntcs.deb
