name: mntcs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y shc
          sudo mkdir /out
          shc -f /src/mntcs.sh -o /out/mntcs

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: mntcs
          path: |
            src/mntcs.conf
            src/mntcs.service
            out/mntcs
