name: mntcs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          cd ./build
          ./build.sh

      # Runs a set of commands using the runners shell
      - name: List
        run: |
          ls
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/build
