name: mntcs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2

      - name: Build
        run: |
          mv $GITHUB_WORKSPACE/src/mntcs.sh $GITHUB_WORKSPACE/src/mntcs

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: mntcs
          path: |
            src/mntcs.conf
            src/mntcs.service
            src/mntcs
